POST http://localhost:3000/api/services
Content-Type:application/json

{
    "email":"umTeter.teste@gamil.com",
    "password":"teste123ss",
    "chats":[],
    "nome":"luiz",
    "phone":"843647232"
}